fly.toml file generated for signal-spawner on 2023-04-27T15:11:07Z

app = "signal-spawner"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "syd"
processes = []

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443